'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NEGATIVE_STRATEGIES} from '@/lib/manual-pair-options';

type Any=any;
function SourceText({article:a}:Any){return <div className="manual-source"><b>{a.headline}</b><small>{a.publisher} · {a.date} · Sự kiện: {a.event_id||'Chưa có'}</small>{/^https?:\/\//i.test(a.payload.article_url||'')&&<a href={a.payload.article_url} target="_blank" rel="noreferrer">Đọc bài gốc ↗</a>}<details><summary>Đọc nội dung văn bản</summary><p className="body-text">{a.payload.body_text||a.payload.article_text||a.payload.content||a.payload.description||'Mở bài gốc để đọc đầy đủ.'}</p></details></div>}
function SourcePicker({title,api,selected,onSelect,disabled}:Any){
 const [q,setQ]=useState(''),[page,setPage]=useState(0),[rows,setRows]=useState<Any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let live=true;setLoading(true);setError('');const timer=setTimeout(()=>{api(`pair_candidates&q=${encodeURIComponent(q)}&page=${page}`).then((r:Any)=>{if(live)setRows(r)}).catch((e:Error)=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)})},250);return()=>{live=false;clearTimeout(timer)}},[api,q,page]);
 async function choose(id:string){setLoading(true);setError('');try{onSelect(await api('pair_source&id='+encodeURIComponent(id)))}catch(e:Any){setError(e.message)}finally{setLoading(false)}}
 return <section className="panel"><h2>{title}</h2><Input aria-label={title+' — tìm bài'} placeholder="Tìm tiêu đề hoặc mã bài…" value={q} disabled={disabled} onChange={e=>{setQ(e.target.value);setPage(0)}}/>{error&&<p className="error" role="alert">{error}</p>}
 <div className="manual-results" aria-busy={loading}>{loading?<p>Đang tải…</p>:rows.length?rows.map(a=><button type="button" className={'list-item'+(selected?.id===a.id?' manual-selected':'')} key={a.id} disabled={disabled||!a.event_id?.trim()} onClick={()=>choose(a.id)}><span>{a.headline}<small>{a.publisher} · {a.event_id||'Chưa có mã sự kiện — nhờ điều phối viên gán tại Dữ liệu & sự kiện'}</small></span></button>):<p className="muted">Không có bài phù hợp. Cần duyệt raw đạt và có ảnh được giữ trước.</p>}</div>
 <div className="actions"><Button variant="outline" disabled={disabled||loading||page===0} onClick={()=>setPage(page-1)}>Trước</Button><span>Trang {page+1}</span><Button variant="outline" disabled={disabled||loading||rows.length<20} onClick={()=>setPage(page+1)}>Tiếp</Button></div>{selected&&<SourceText article={selected}/>}</section>
}
export default function ManualPairBuilder({api,stats,busy,perform,onCreated,open,dirty}:Any){
 const [article,setArticle]=useState<Any>(),[source,setSource]=useState<Any>(),[image,setImage]=useState<Any>(),[batch,setBatch]=useState(''),[strategy,setStrategy]=useState(''),[reason,setReason]=useState(''),[evidence,setEvidence]=useState(''),[mine,setMine]=useState<Any[]>([]),[listError,setListError]=useState('');
 useEffect(()=>{let live=true;api('manual_pairs').then((r:Any)=>{if(live){setMine(r);setListError('')}}).catch((e:Error)=>{if(live)setListError(e.message)});return()=>{live=false}},[api,stats]);
 const batches=(stats?.batches||[]).filter((b:Any)=>b.active),sameEvent=article&&source&&article.event_id===source.event_id,sameImage=image&&article?.images.some((i:Any)=>i.asset_id===image.asset_id);
 const ready=article&&source&&image&&article.id!==source.id&&!sameEvent&&!sameImage&&batches.some((b:Any)=>b.id===batch)&&strategy&&reason.trim().length>=10&&evidence.trim();
 return <><div className="note">Tự chọn cặp âm khó theo N3–N7. Hai bài phải được duyệt và thuộc hai sự kiện khác nhau. Sau khi tạo, bạn điền phiếu V2; người thứ hai nhận cặp trong mục Gán nhãn cặp và không thấy chiến lược hoặc lý do đề xuất của bạn.</div>
 {!batches.length&&<p className="warning">Chưa có đợt đang mở. Điều phối viên tạo hoặc mở đợt trong Dữ liệu & sự kiện trước khi tạo cặp.</p>}
 <div className="dashboard-grid"><SourcePicker title="1. Chọn bài văn bản" api={api} selected={article} disabled={busy} onSelect={(a:Any)=>{setArticle(a);dirty(true)}}/><div><SourcePicker title="2. Chọn bài chứa ảnh thay thế" api={api} selected={source} disabled={busy} onSelect={(a:Any)=>{setSource(a);setImage(undefined);dirty(true)}}/>{source&&<section className="panel"><h3>Chọn một ảnh đã được giữ</h3><div className="manual-images">{source.images.map((i:Any)=><button type="button" key={i.id} className={image?.id===i.id?'manual-selected':''} aria-label={'Chọn ảnh '+i.id} aria-pressed={image?.id===i.id} disabled={busy} onClick={()=>{setImage(i);dirty(true)}}><img loading="lazy" src={'/api/media/'+i.asset_id} alt={i.payload.caption||'Ảnh '+i.id}/><small>{i.payload.caption||i.id}</small></button>)}</div>{image&&<><p>{image.payload.caption||'Ảnh không có caption'}</p><a href={'/api/media/'+image.asset_id} target="_blank" rel="noreferrer">Mở ảnh đầy đủ ↗</a><small>{image.id}</small></>}</section>}</div></div>
 {(sameEvent||sameImage)&&<p className="warning">{sameEvent?'Hai bài đang cùng sự kiện. Chọn bài thuộc sự kiện khác.':'Ảnh này đã xuất hiện trong bài văn bản. Chọn ảnh khác.'}</p>}
 <section className="panel"><h2>3. Ghi căn cứ rồi gán nhãn</h2><form onSubmit={e=>{e.preventDefault();perform(async()=>{const p=await api('manual_pair_create',{article_id:article?.id,image_id:image?.id,batch,strategy,reason,evidence:evidence.split('\n').map(u=>u.trim()).filter(Boolean)});dirty(false);onCreated(p)},'Đã tạo cặp và mở phiếu V2 của bạn.')}}><fieldset disabled={busy}>
 <div className="dashboard-grid"><label className="field"><span>Đợt gán nhãn</span><select required value={batch} onChange={e=>{setBatch(e.target.value);dirty(true)}}><option value="">Chọn đợt…</option>{batches.map((b:Any)=><option value={b.id} key={b.id}>{b.name} · {b.kind}</option>)}</select></label><label className="field"><span>Chiến lược mẫu âm khó</span><select required value={strategy} onChange={e=>{setStrategy(e.target.value);dirty(true)}}><option value="">Chọn N3–N7…</option>{Object.entries(NEGATIVE_STRATEGIES).map(([k,v])=><option key={k} value={k}>{k} · {v}</option>)}</select></label></div>
 <label className="field"><span>Điểm giống dễ gây nhầm và điểm khác về sự kiện</span><Textarea required minLength={10} maxLength={10000} rows={4} placeholder="Ví dụ: cùng cảnh ngập đường, nhưng ảnh chụp ở Huế năm 2020 còn bài nói về Đà Nẵng năm 2025…" value={reason} onChange={e=>{setReason(e.target.value);dirty(true)}}/></label>
 <label className="field"><span>URL bằng chứng — mỗi dòng một đường dẫn</span><Textarea required rows={3} placeholder="Đường dẫn bài nguồn hoặc tài liệu xác minh thời gian, địa điểm, đối tượng…" value={evidence} onChange={e=>{setEvidence(e.target.value);dirty(true)}}/></label>
 <p className="muted">Đây là đề xuất mẫu âm khó. Nhãn và độ khó được xác định qua 6 câu hỏi V2; không đủ bằng chứng thì chọn Mơ hồ. Không tự động chốt Ngoài ngữ cảnh hoặc ép điểm Khó.</p><Button type="submit" disabled={busy||!ready}>{busy?'Đang lưu…':'Tạo cặp & gán nhãn thủ công'}</Button></fieldset></form></section>
 <section className="panel"><h2>Cặp bạn đã tự tạo</h2>{listError&&<p className="error">{listError}</p>}{!mine.length?<p className="muted">Chưa có cặp tự tạo. Kết quả sẽ được lưu ở đây để mở lại bản nháp và theo dõi duyệt.</p>:mine.map(p=><div className="mini-stat" key={p.id}><span>{p.headline}<small>{p.strategy} · {p.state==='approved'?'Đã chốt':p.state==='review'?'Chờ kiểm định':p.annotation_state==='submitted'?'Đã gửi — chờ người thứ hai':'Bản nháp / đang gán nhãn'} · {p.id}</small></span>{p.annotation_state&&<Button variant="outline" onClick={()=>open('pair',p.id)} disabled={busy}>Mở phiếu</Button>}</div>)}<small>Tối đa 40 cặp gần nhất. Điều phối viên xuất toàn bộ tại Xuất & nhật ký.</small></section></>;
}
